#:schema node_modules/wrangler/config-schema.json
name = "my-wine-menu"
compatibility_date = "2024-05-02"
compatibility_flags = [ "nodejs_compat" ]

# R2の紐付けをコードで直接定義（画面の設定を無視させます）
[[r2_buckets]]
binding = "WINE_IMAGES"
bucket_name = "wine-images" # あなたが最後に作り直したバケット名が違う場合は、その名前に変えてください。
